config/routes.rb
Rails.application.routes.draw do
  
  root to: 'visitors#home'

  devise_for :users, controllers: {sessions: 'sessions'}

  get '/home', to: 'visitors#home', as: 'home'
  get '/mysol', to: 'visitors#mysol', as: 'mysol'
  get '/destination', to: 'visitors#destination', as: 'destination'
  get '/solblog', to: 'visitors#solblog', as: 'solblog'
  get '/travel', to: 'visitors#travel', as: 'travel'

  resources :blogs
  resources :locations

  post '/photos/create', to: 'blogs#create_photo', as: 'photos'
  delete '/photos/:id', to: 'blogs#destroy_photo', as: 'photo'
  put '/destination/select_top', to: 'blogs#select_top', as: 'select_top'
  post '/support', to: 'visitors#support', as: 'support'
  post '/solblog', to: 'visitors#post_comment', as: 'post_comment'

  get '/solblog_feed', to: 'visitors#solblog_feed', as: 'solblog_feed', default: {:format => 'rss'}

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
	
	before_filter :get_locations

	def home
		@main_blog = Blog.latest_blog
	end

	def solblog
		@main_blogs = Blog.main_blogs.paginate(:page => params[:page], :per_page => 1)
		@selected_blog = @main_blogs.first
		@blog_titles = Blog.main_blogs
		@comment_show = params[:comment_show] || false

		if params[:page].blank? && !params[:blog_id].blank?
			@selected_blog = Blog.where(id: params[:blog_id]).first
		end
	end

	def mysol
		@mysol_blog = Blog.my_sol_blogs.first
	end

	def destination
		@location = Location.includes(:blogs).includes(:photos).find_by_name params[:name]
		@photo = @location.photo.picture.url
		@photos = @location.all_photos.limit 12
		@destination = @location.blogs.destination.first
		@eat_blogs = @location.blogs.eat
		@stay_blogs = @location.blogs.stay
		@play_blogs = @location.blogs.play
		@featured_blogs = @location.sub_blogs.featured
	end

	def travel
	end

	def support
		SupportMailer.notify(params[:support][:email], params[:support][:title], params[:support][:body]).deliver

		redirect_to travel_path, notice: 'Email is successfully sent.'
	end

	def post_comment
		@blog = Blog.find(params[:blog_id])
		@comment = @blog.comments.create permit_comment_params
		redirect_to solblog_path(page: params[:page], comment_show: true) + "#comment-form"
	end

	def solblog_feed
		@feed_blogs = Blog.main_blogs

		render :template => '/feed/feed.rss.builder', :layout => false
	end

	def permit_comment_params
		params.require(:comment).permit(:name, :comment)
	end

end

app/views/visitors/destination.html.erb
<% title "The Simple SOL" %>
<div>
    <div class="header">
        <%= link_to destination_path(name: params[:name]) do %>
            <div class='title'><%= params[:name] %></div>
            <%= image_tag @photo, id:"dest_blog_img", class: "blog_big_img", title: @photo %>
        <% end %>
    </div>
    <div class="submenu">
        <div style="width:15%" class="pull-left"><hr/></div>
        <%= link_to 'eat', 'javascript:void(0)', data: {target: '#eat_blog_div'}, class: "submenu_title pull-left" %>
        <div style="width:14%;" class="pull-left"><hr/></div>
        <%= link_to 'play', 'javascript:void(0)', data: {target: '#play_blog_div'}, class: 'submenu_title pull-left' %>
        <div style="width:14%;" class="pull-left"><hr/></div>
        <%= link_to 'stay', 'javascript:void(0)', data: {target: '#stay_blog_div'}, class: 'submenu_title pull-left' %>
        <div style="width:15%;" class="pull-left"><hr/></div>
    </div>

    <div id="location_blog_div">
        <div class="sol_blog_section">
            <div class="pull-left hr_div" style="width:40%"><hr/><hr/></div>
            <div class="pull-left" style="width:20%"><h2>STORY</h2></div>
            <div class="pull-left hr_div" style="width:40%"><hr/><hr/></div>
            <div style="clear: both;"></div>
        </div>
        <div>
            <% unless @destination.nil? %>
                <div class="blog_title title_field">
                    <%= @destination.title %>
                </div>
                <div>
                    <%= image_tag @destination.picture.url, class: "blog_mid_img" %>
                </div>
                <div class="blog_content">
                    <%= raw @destination.body %>
                </div>
            <% end %>
        </div>
        <div>
            <div class="blog_line_bar">
                <div class="pull-left hr_div" style="width:40%"><hr/><hr/></div>
                <div class="pull-left" style="width:20%"><h2>TOP <%= @featured_blogs.count   %></h2></div>
                <div class="pull-left hr_div" style="width:40%"><hr/><hr/></div>
                <div style="clear: both;"></div>
            </div>

            <div class="row">
                <div class="col-sm-8 col-xs-12">
                    <% @featured_blogs.each_with_index do |blog, index| %>
                        <%= image_tag blog.picture.url, id: "featured-img-#{index}", class: "#{index == 0 ? 'show' : 'hidden'} featured_image" %>
                    <% end %>
                </div>
                <div class="col-sm-4 col-xs-12">
                    <div class="row">
                        <div class="col-sm-12 col-xs-12" data-current="0" data-total="<%= @featured_blogs.count %>" id="control-bar">
                            <div class="col-sm-4 col-xs-4 pull-left">
                                <%= image_tag '/assets/themes/light/panel-prev-big.png', class: 'blog_nav_img', id: "featured-left"%>
                            </div>
                            <div id="featured-status" class="col-sm-4 col-xs-4 pull-left"></div>
                            <div class="col-sm-4 col-xs-4 pull-left">
                                <%= image_tag '/assets/themes/light/panel-next-big.png', class: 'blog_nav_img', id: "featured-right"%>
                            </div>
                        </div>
                    </div>
                    <% @featured_blogs.each_with_index do |blog, index| %>
                        <span id="featured-blog-<%=index %>", class="<%= index == 0 ? 'show' : 'hidden'%> featured_blog" >
                            <%= raw blog.body%>
                        </span>
                    <% end %>
                </div>
            </div>
        </div>
        <div>
            <div class="blog_line_bar">
                <div class="pull-left hr_div" style="width:40%"><hr/><hr/></div>
                <div class="pull-left" style="width:20%"><h2>PHOTOS</h2></div>
                <div class="pull-left hr_div" style="width:40%"><hr/><hr/></div>
                <div style="clear: both;"></div>
            </div>

            <div id="pinterest">
                <div id="pinterest_photo">
                    <% @photos.each do |photo| %>
                        <div>
                            <%= link_to photo.picture.url do %>
                                <%= image_tag photo.picture.url(:thumb), style: "width:150px" %>
                            <% end %>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>
    </div>


    <div id="eat_blog_div">
        <div class="blog_line_bar">
            <div class="pull-left hr_div" style="width:40%"><hr/><hr/></div>
            <div class="pull-left" style="width:20%"><h2>EAT</h2></div>
            <div class="pull-left hr_div" style="width:40%"><hr/><hr/></div>
            <div style="clear: both;"></div>
        </div>
        <% @eat_blogs.each do |blog| %>
            <div class="row">
                <div class="col-sm-8">
                    <%= link_to url_with_protocol(blog.link_url) do %>
                        <%= image_tag blog.picture.url %>
                    <% end %>
                </div>
                <div class="col-sm-4">
                    <h4><%= blog.title.upcase %></h4>
                    <span class="featured_blog_content">
                        <%= raw blog.body %>
                    </span>
                </div>
                                
            </div>
            <hr class="clearfix large_margin" />
        <% end %>
        <br />
        <br />
    </div>

    <div id="play_blog_div">
        <div class="blog_line_bar">
            <div class="pull-left hr_div" style="width:40%"><hr/><hr/></div>
            <div class="pull-left" style="width:20%"><h2>PLAY</h2></div>
            <div class="pull-left hr_div" style="width:40%"><hr/><hr/></div>
            <div style="clear: both;"></div>
        </div>
        <% @play_blogs.each do |blog| %>
            <div class="row">
                <div class="col-sm-8">
                    <%= link_to url_with_protocol(blog.link_url) do %>
                        <%= image_tag blog.picture.url %>
                    <% end %>
                </div>
                <div class="col-sm-4">
                    <h4><%= blog.title.upcase %></h4>
                    <span class="featured_blog_content">
                        <%= raw blog.body %>
                    </span>
                </div>
            </div>
            <hr class="large_margin" />
        <% end %>
        <br />
        <br />
    </div>

    <div id="stay_blog_div">
        <div class="blog_line_bar">
            <div class="pull-left hr_div" style="width:40%"><hr/><hr/></div>
            <div class="pull-left" style="width:20%"><h2>STAY</h2></div>
            <div class="pull-left hr_div" style="width:40%"><hr/><hr/></div>
            <div style="clear: both;"></div>
        </div>
        <% @stay_blogs.each do |blog| %>
            <div class="row">
                <div class="col-sm-8">
                    <%= link_to url_with_protocol(blog.link_url) do %>
                        <%= image_tag blog.picture.url %>
                    <% end %>
                </div>
                <div class="col-sm-4">
                    <h4><%= blog.title.upcase %></h4>
                    <span class="featured_blog_content">
                        <%= raw blog.body %>
                    </span>
                </div>
            </div>
            <hr class="large_margin" />
        <% end %>
        <br />
        <br />
    </div>
    
</div>

app/views/visitors/home.html.erb
<% title "The Simple SOL" %>
<div class="sol_blog">
    <div class="col-sm-12">
        <div id="gallery_large" class="image_gallery">
            <ul id="myGallery">
                <% @locations.each do |l| %>
                    <li><%= image_tag l.photo.picture.url, title: l.name, id: "#{l.name}", data: {target: "#{destination_url(name: l.name)}"} %></li>
                <% end %>
            </ul>
        </div>
        <div id="gallery_small" class="image_gallery">
            <ul class="bxslider">
                <% @locations.each do |l| %>
                    <li>
                        <%= image_tag l.photo.picture.url, title: l.name, data: {target: "#{destination_url(name: l.name)}"} %>
                    </li>
                <% end %>
            </ul>
        </div>
    </div>
    <div class="col-sm-12">
        <div class="sol_blog_section">
            <div class="line_bar">
                <div class="pull-left hr_div" style="width:35%;"><hr/><hr/></div>
                <div class="pull-left" style="width:30%;"><h2>SOL BLOG</h2></div>
                <div class="pull-left hr_div" style="width:35%;"><hr/><hr/></div>
                <div style="clear: both;"></div>
            </div>
            <div class="sol_blog_main">
                <% unless @main_blog.nil? %>
                    <div class="blog_title title_field">
                        <%= link_to solblog_path do %>
                            <%= @main_blog.title %>
                        <% end %>
                    </div>
                    <div>
                        <%= image_tag @main_blog.picture.url, class: "blog_mid_img" %>
                    </div>
                    <div class="blog_content">
                        <%= raw @main_blog.body %>
                    </div>
                <% end %>
            </div>
        </div>
        <div class="sol_blog_section">
            <div class="line_bar">
                <div class="pull-left hr_div" style="width:32%;"><hr/><hr/></div>
                <div class="pull-left" style="width:36%;"><h2>INSTAGRAM</h2></div>
                <div class="pull-left hr_div" style="width:32%;"><hr/><hr/></div>
                <div style="clear: both;"></div>
            </div>
            <div id="wrapper">
                <div id="instafeed"></div>
            </div>
        </div>    
        </div>
    </div>
</div>
<br />
<br />

app/views/visitors/index.html.erb
<h3>Welcome</h3>

app/views/visitors/mysol.html.erb
<% title "My SOL" %>
<div class="col-sm-12">
    <% unless @mysol_blog.nil? %>
        <div class="about_image">
            <%= image_tag @mysol_blog.picture.url, class: "blog_big_img" %>
        </div>
        <div class="quote text-center">
            <div class="quote_font">&ldquo;</div>
            <div class="quote_text">
                &nbsp;&nbsp;
                <%= @mysol_blog.title %>
                &nbsp;&nbsp;</div>
            <div class="quote_font">&rdquo;</div>
        </div>
        <hr />
        <div class="about_content">
            <%= raw @mysol_blog.body %>
        </div>
    <% end %>
    <hr />
    <br />
    <br />
    <br />
</div>

app/views/visitors/solblog.html.erb
<div class="main">
    <div>
        <h2>SOL BLOG</h2>
    </div>
    
    <% title @selected_blog.title %>
    <% description @selected_blog.title %>
    <div class="blog_section c-no-padding-bottom">
        <div class="blog_title">
            <div class="title_field"><%= @selected_blog.title %></div>
            <div class="date_field"><%=  @selected_blog.created_at.strftime "%D" %></div>
        </div>
        <div style="clear:both"></div>
        <div>
            <%= image_tag @selected_blog.picture.url, class: "" %>
        </div>
        <div class="blog_content">
            <%= raw @selected_blog.body %>
            <!-- This part is for floating menu
            <div id="fl_menu">
            <div class="label" style="opacity:0.5;">MENU</div>
            <div class="menu">
                <% @blog_titles.each do |blog_menu| %>
                    <%= link_to blog_menu.title, solblog_path(blog_id: blog_menu.id), class: "menu_item" %>
                <% end %>
            </div>
            -->
        </div>
        </div>
        <br />
        <table class="table table-bordered">
            <tr>
                <td class="c-no-side-border">
                    <%= link_to "http://www.twitter.com/share?url=" + root_url + "solblog?blog_id=" + @selected_blog.id.to_s, class: "share_icon", title: "Share on Twitter", target: "_blank" do %>
                        <%= image_tag "share_twitter.jpg" %>
                    <% end %>
                    <%= link_to "http://www.facebook.com/sharer.php?u=" + root_url + "solblog?blog_id=" + @selected_blog.id.to_s + "&t=" + @selected_blog.title, class: "share_icon", title: "Share on Facebook", target: "_blank" do %>
                        <%= image_tag "share_facebook.jpg" %>
                    <% end %>
                </td>
                <td class="c-vertical-middle c-no-side-border">
                    <span>FOLLOW ON BLOG LOVIN'</span>
                </td>
                <td class="c-vertical-middle c-no-side-border">
                    <a href="#comment_input" id="leave_comment" class="comment">LEAVE A COMMENT</a>
                    &nbsp;/&nbsp;
                    <a href="#comment_show" id="view_comment" class="comment"><%= @selected_blog.comments.count %> COMMENTS</a>
                </td>
                <td class="c-vertical-middle c-no-side-border">
                    <%= link_to (image_tag 'feed_icon_large.png', size:"18x18", alt: "RSS Feed"), solblog_feed_path, target: "_blank" %> 
                </td>
            </tr>
        </table>
    </div>
    <div id="comment_input" class="row" style="<%= @comment_show == 'true' ? '' : 'display: none;' %>">
        <div class="col-sm-10 col-sm-offset-1">
            <% @selected_blog.comments.each do |comment| %>
                <div  class="c-comment-area c-font-dayroman">
                    <h3 class="c-comment-name"><%= comment.name %></h3>
                    <p class="c-font-dayroman c-comment-content"><%= raw comment.comment %></p>
                </div>
            <% end %>
        </div>
        <br />
        <br />
        <div class="col-sm-8 col-sm-offset-2">
            <a href="#" id="comment-form"></a>
            <%= form_for :comment, url: post_comment_path(blog_id: @selected_blog.id, page: params[:page]), method: :post do |f| %>
                <div class="form-group">
                    <%= f.label(:name, 'NAME') %>
                    <%= f.text_field :name, class: 'form-control' %>
                </div>
                <div class="form-group">
                    <%= f.label(:comment, 'COMMENT') %>
                    <%= f.text_area :comment, rows: 5, class: 'form-control' %>
                </div>
                <button type="submit" class="btn btn-default">SUBMIT</button>
                <br />
                <br />
            <% end %>
            <a href="#leave_comment" id="comment_hide"><img src="/assets/panel-up-big.png" style="opacity:0.5;" /></a>
        </div>
    </div>
    <div id="comment_show" class="row" style="display:none;" >
        <div class="col-sm-10 col-sm-offset-1">
            <% @selected_blog.comments.each do |comment| %>
                <div  class="c-comment-area">
                    <h3 class="c-comment-name"><%= comment.name %></h3>
                    <p class="c-font-dayroman c-comment-content"><%= raw comment.comment %></p>
                </div>
            <% end %>
            <a href="#leave_comment" id="comment_hide1"><img src="/assets/panel-up-big.png" style="opacity:0.5;" /></a>
        </div>
    </div>
    <hr />
    
    <div class="col-md-8 col-md-offset-2" style="text-align:center">
        <%= will_paginate @main_blogs, renderer: BootstrapPagination::Rails, :inner_window => 1, :outer_window => 1, :previous_label => "PREV", :next_label => "NEXT", params: {comment_show: false} %>  
    </div>
    
    <br />
    <br />
</div>

<script>
    //config
    $float_speed=1500; //milliseconds
    $float_easing="easeOutQuint";
    $menu_fade_speed=500; //milliseconds
    $closed_menu_opacity=0.5;
     
    //cache vars
    $fl_menu=$("#fl_menu");
    $fl_menu_menu=$("#fl_menu .menu");
    $fl_menu_label=$("#fl_menu .label");
     
    $(window).load(function() {
        //menuPosition=$('#fl_menu').position().top;
        menuPosition=$('.blog_title').position().top;
        $fl_menu_label.fadeTo($menu_fade_speed, $closed_menu_opacity);
        FloatMenu();
        $fl_menu.hover(
            function(){ //mouse over
                $fl_menu_label.fadeTo($menu_fade_speed, 1);
                $fl_menu_menu.fadeIn($menu_fade_speed);
            },
            function(){ //mouse out
                $fl_menu_label.fadeTo($menu_fade_speed, $closed_menu_opacity);
                $fl_menu_menu.fadeOut($menu_fade_speed);
            }
        );
    });
     
    $(window).scroll(function () {
        FloatMenu();
    });
     
    function FloatMenu(){
        var scrollAmount=$(document).scrollTop();
        var newPosition=menuPosition+scrollAmount;
        if($(window).height()<$fl_menu.height()+$fl_menu_menu.height()){
            $fl_menu.css("top", '150px');
        } else {
            $fl_menu.stop().animate({top: newPosition}, $float_speed, $float_easing);
        }
    }
</script>

app/views/visitors/travel.html.erb
<% title "Travel Consultant" %>
<div class="row">
	<div class="col-sm-8 col-sm-offset-2">
		<%= form_for :support, url: support_path, method: :post do |f| %>
		  <div class="form-group">
		    <%= f.label(:email, 'EMAIL') %>
		    <%= f.text_field :email, class: 'form-control' %>
		  </div>
		  <div class="form-group">
		    <%= f.label(:title, 'TITLE') %>
		    <%= f.text_field :title, class: 'form-control' %>
		  </div>
		  <div class="form-group">
		    <%= f.label(:body, 'BODY') %>
		    <%= f.text_area :body, rows: 5, class: 'form-control' %>
		  </div>
		  <button type="submit" class="btn btn-default">SUBMIT</button>
		<% end %>
	</div>
	<br />
	<br />
</div>